export interface ListItemsValueType {
  name?: string
  title?: string
  group: string
  episode_id?: number
  opening_crawl?: string
  director?: string
  producer?: string
  release_date?: Date
  species?: string[]
  starships?: string[]
  vehicles?: string[]
  characters?: string[]
  planets?: string[]
  url?: string
  created?: string
  MGLT?: string
  model?: string
  starship_class?: string
  manufacturer?: string
  cost_in_credits?: string
  length?: string
  crew?: string
  passengers?: string
  max_atmosphering_speed?: string
  hyperdrive_rating?: string
  cargo_capacity?: string
  consumables?: string
  films?: string[]
  pilots?: string[]
  edited?: string
  vehicle_class?: string
  classification?: string
  designation?: string
  average_height?: string
  average_lifespan?: string
  eye_colors?: string
  hair_colors?: string
  skin_colors?: string
  language?: string
  homeworld?: string
  people?: string[]
  diameter?: string
  rotation_period?: string
  orbital_period?: string
  gravity?: string
  population?: string
  climate?: string
  terrain?: string
  surface_water?: string
  residents?: string[]
}